   
-- 상품 테이블 (PRODUCTS) 생성
CREATE TABLE PRODUCTS (
    PID NUMBER(10) PRIMARY KEY,             -- 상품 고유번호 (PK, 자동 증가)
    PNAME VARCHAR2(100) NOT NULL,           -- 상품명
    PRICE NUMBER(10,2) NOT NULL,            -- 상품 가격 (소수점 2자리)
    STOCK NUMBER(10) NOT NULL               -- 재고 수량
);

ALTER TABLE PRODUCTS MODIFY (PRICE NUMBER(10, 2));

-- 시퀀스 생성
CREATE SEQUENCE PRODUCTS_PID_SEQ START WITH 1 INCREMENT BY 1;

-- 트리거 생성
CREATE OR REPLACE TRIGGER PRODUCTS_ON_INSERT
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
    SELECT PRODUCTS_PID_SEQ.NEXTVAL INTO :NEW.PID FROM DUAL;
END;
/

-- 테스트용 샘플 데이터 추가
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('그램', 1200000, 10);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('스마트폰', 800000, 20);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('태블릿', 500000, 15);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('무선 이어폰', 200000, 50);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('스마트워치', 450000, 30);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('노트북', 1500000, 5);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('키보드', 80000, 100);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('마우스', 45000, 120);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('모니터', 350000, 25);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('웹캠', 75000, 40);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('외장하드', 110000, 60);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('USB 메모리', 15000, 200);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('헤드셋', 95000, 75);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('블루투스 스피커', 60000, 90);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('프로젝터', 720000, 8);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('TV', 950000, 12);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('공기청정기', 300000, 18);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('로봇청소기', 550000, 22);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('커피머신', 250000, 35);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('토스터기', 55000, 80);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('에어프라이어', 130000, 45);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('전기밥솥', 180000, 28);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('드라이기', 40000, 110);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('전동칫솔', 65000, 65);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('운동화', 99000, 55);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('티셔츠', 25000, 150);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('청바지', 78000, 40);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('백팩', 125000, 30);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('손목시계', 220000, 25);
INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('자전거', 400000, 7);
COMMIT;



-- 1. 테이블의 모든 데이터 삭제
TRUNCATE TABLE PRODUCTS;

-- 2. 기존 시퀀스 삭제
DROP SEQUENCE PRODUCTS_SEQ;

-- 3. 시퀀스 재생성 (1부터 시작)
CREATE SEQUENCE PRODUCTS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 4. 트리거 재컴파일
ALTER TRIGGER PRODUCTS_ON_INSERT COMPILE;

INSERT INTO PRODUCTS (PNAME, PRICE, STOCK) VALUES ('새 상품', 10000, 10);
COMMIT;