/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.43
 * Generated at: 2025-08-18 08:00:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import com.company1.DBManager;

public final class product_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common-jsp/header.jsp", Long.valueOf(1755501566831L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.company1.DBManager");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

request.setCharacterEncoding("UTF-8");

// 페이지네이션 및 검색 기능을 위한 변수 설정
int currentPage = 1;
int pageSize = 10; // 한 페이지당 표시 수
String search = request.getParameter("search");

if(request.getParameter("page") != null) {
    currentPage = Integer.parseInt(request.getParameter("page"));
}
int startRow = (currentPage - 1) * pageSize;

Connection conn = null;
PreparedStatement pstmt = null;
ResultSet rs = null;
PreparedStatement pstmtCount = null;
ResultSet rsCount = null;

int totalRows = 0;
boolean hasData = false;

try {
    conn = DBManager.getDBConnection();

    // 총 상품 수 (검색 포함) - Oracle 문법 사용
    String countSql = "SELECT COUNT(*) FROM PRODUCTS";
    if(search != null && !search.isEmpty()) {
        countSql += " WHERE PNAME LIKE ?";
    }
    pstmtCount = conn.prepareStatement(countSql);
    if(search != null && !search.isEmpty()) {
        pstmtCount.setString(1, "%" + search + "%");
    }
    rsCount = pstmtCount.executeQuery();
    if(rsCount.next()) totalRows = rsCount.getInt(1);
    
    // 첫 번째 PreparedStatement 정리
    if(rsCount != null) rsCount.close();
    if(pstmtCount != null) pstmtCount.close();

    // 상품 조회 (검색 + 페이징) - Oracle 문법 사용
    String sql = "SELECT * FROM (SELECT ROWNUM rnum, p.* FROM (SELECT * FROM PRODUCTS";
    if(search != null && !search.isEmpty()) {
        sql += " WHERE PNAME LIKE ?";
    }
    sql += " ORDER BY PID ASC) p WHERE ROWNUM <= ?) WHERE rnum > ?";

    pstmt = conn.prepareStatement(sql);
    int idx = 1;
    if(search != null && !search.isEmpty()) {
        pstmt.setString(idx++, "%" + search + "%");
    }
    pstmt.setInt(idx++, startRow + pageSize);
    pstmt.setInt(idx++, startRow);

    rs = pstmt.executeQuery();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>상품 목록</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- 헤더 포함 -->\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul class=\"main-menu\">\r\n");
      out.write("                <li><a href=\"index.jsp\">메인 페이지</a></li>\r\n");
      out.write("                <li><a href=\"#\">사용자 관리</a></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">상품 관리</a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"product_list.jsp\">상품 목록</a></li>\r\n");
      out.write("                        <li><a href=\"product_add.jsp\">상품 추가</a></li>\r\n");
      out.write("                        <li><a href=\"product_main.jsp\">상품 메인</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"order_list.jsp\">주문 관리</a></li>\r\n");
      out.write("                <li><a href=\"#\">그룹웨어</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <h1>상품 목록</h1>\n");
      out.write("\n");
      out.write("    <!-- 메시지 표시 -->\n");
      out.write("    ");

    String message = request.getParameter("message");
    String error = request.getParameter("error");
    if (message != null) {
        if ("updated".equals(message)) {
            out.println("<div class='message success'>상품이 성공적으로 수정되었습니다.</div>");
        } else if ("deleted".equals(message)) {
            out.println("<div class='message success'>상품이 성공적으로 삭제되었습니다.</div>");
        } else if ("added".equals(message)) {
            out.println("<div class='message success'>상품이 성공적으로 추가되었습니다.</div>");
        }
    }
    if (error != null) {
        if ("notfound".equals(error)) {
            out.println("<div class='message error'>해당 상품을 찾을 수 없습니다.</div>");
        } else if ("db".equals(error)) {
            String detail = request.getParameter("detail");
            out.println("<div class='message error'>데이터베이스 오류가 발생했습니다.</div>");
            if (detail != null) {
                out.println("<div class='message error' style='font-size: 12px; margin-top: 5px;'>상세 오류: " + detail + "</div>");
            }
        } else if ("invalid".equals(error)) {
            out.println("<div class='message error'>잘못된 요청입니다.</div>");
        }
    }
    
      out.write("\n");
      out.write("\n");
      out.write("    <!-- 검색 -->\n");
      out.write("    <form method=\"get\" action=\"product_list.jsp\" style=\"text-align:center; margin-bottom:10px;\">\n");
      out.write("        <input type=\"text\" name=\"search\" value=\"");
      out.print( (search!=null)?search:"" );
      out.write("\" placeholder=\"상품명 검색\">\n");
      out.write("        <input type=\"submit\" value=\"검색\">\n");
      out.write("        ");
 if(search != null && !search.isEmpty()) { 
      out.write("\n");
      out.write("            <a href=\"product_list.jsp\">전체보기</a>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <table class=\"product-table\">\n");
      out.write("    <thead>\n");
      out.write("    <tr>\n");
      out.write("        <th>상품번호</th>\n");
      out.write("        <th>상품명</th>\n");
      out.write("        <th>가격</th>\n");
      out.write("        <th>재고</th>\n");
      out.write("        <th>관리</th>\n");
      out.write("    </tr>\n");
      out.write("    </thead>\n");
      out.write("    <tbody>\n");
      out.write("    ");

    int displayNumber = (currentPage - 1) * pageSize; // 페이징을 고려한 시작 번호
    while(rs.next()) {
        hasData = true;
        displayNumber++; // 1부터 시작하는 연속 번호
    
      out.write("\n");
      out.write("    <tr>\n");
      out.write("        <td>");
      out.print( displayNumber );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( rs.getString("PNAME") );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( String.format("%,d", rs.getInt("PRICE")) );
      out.write("원</td>\n");
      out.write("        <td>");
      out.print( rs.getInt("STOCK") );
      out.write("개</td>\n");
      out.write("        <td>\n");
      out.write("            <a href=\"product_edit.jsp?pid=");
      out.print( rs.getInt("PID") );
      out.write("\" class=\"btn-small\">수정</a>\n");
      out.write("            <a href=\"product_delete.jsp?pid=");
      out.print( rs.getInt("PID") );
      out.write("\" \n");
      out.write("               class=\"btn-small btn-danger\" \n");
      out.write("               onclick=\"return confirm('정말 삭제하시겠습니까?')\">삭제</a>\n");
      out.write("        </td>\n");
      out.write("    </tr>\n");
      out.write("    ");

    }
    
    if(!hasData) {
    
      out.write("\n");
      out.write("    <tr>\n");
      out.write("        <td colspan=\"5\">\n");
      out.write("            ");
 if(search != null && !search.isEmpty()) { 
      out.write("\n");
      out.write("                검색 결과가 없습니다.\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                등록된 상품이 없습니다. <a href=\"product_add.jsp\" class=\"btn\">첫 번째 상품 추가하기</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </td>\n");
      out.write("    </tr>\n");
      out.write("    ");

    }
    
      out.write("\n");
      out.write("    </tbody>\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <!-- 페이징 -->\n");
      out.write("    ");
 if(hasData && totalRows > pageSize) { 
      out.write("\n");
      out.write("    <div class=\"pagination\">\n");
      out.write("    ");

    int totalPages = (int)Math.ceil((double)totalRows / pageSize);
    for(int i=1; i<=totalPages; i++) {
        if(i==currentPage) {
            out.print("<b>"+i+"</b>");
        } else {
            out.print("<a href='product_list.jsp?page="+i+(search!=null?"&search="+search:"")+"'>"+i+"</a>");
        }
    }
    
      out.write("\n");
      out.write("    </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");

} catch(Exception e) {
    e.printStackTrace();
    out.println("<div class='error-message'>데이터베이스 오류가 발생했습니다: " + e.getMessage() + "</div>");
} finally {
    try {
        if(rs != null) rs.close();
        if(pstmt != null) pstmt.close();
        if(rsCount != null) rsCount.close();
        if(pstmtCount != null) pstmtCount.close();
        if(conn != null) conn.close();
    } catch(SQLException e) {
        e.printStackTrace();
    }
}

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
